// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHu7OV5HNB8zNAcxG30GakLIaLxVDBLLg',
    appId: '1:688370582507:web:68e551d1395086676a8fae',
    messagingSenderId: '688370582507',
    projectId: 'mamba-growth-kn',
    authDomain: 'mamba-growth-kn.firebaseapp.com',
    storageBucket: 'mamba-growth-kn.firebasestorage.app',
    measurementId: 'G-XFNH9NWHZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTC7zhcueotJTAxLNT-JF_ntq92pIEeyE',
    appId: '1:688370582507:android:8070615b77b12a636a8fae',
    messagingSenderId: '688370582507',
    projectId: 'mamba-growth-kn',
    storageBucket: 'mamba-growth-kn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Z7_Oh9LUVxjec8aNLkKyYnYOsGW2h5g',
    appId: '1:688370582507:ios:97f19877440373db6a8fae',
    messagingSenderId: '688370582507',
    projectId: 'mamba-growth-kn',
    storageBucket: 'mamba-growth-kn.firebasestorage.app',
    iosClientId: '688370582507-838k6vrg080ffmp9huij7u93i32fa3v7.apps.googleusercontent.com',
    iosBundleId: 'com.kndeveloper.mambaGrowth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Z7_Oh9LUVxjec8aNLkKyYnYOsGW2h5g',
    appId: '1:688370582507:ios:97f19877440373db6a8fae',
    messagingSenderId: '688370582507',
    projectId: 'mamba-growth-kn',
    storageBucket: 'mamba-growth-kn.firebasestorage.app',
    iosClientId: '688370582507-838k6vrg080ffmp9huij7u93i32fa3v7.apps.googleusercontent.com',
    iosBundleId: 'com.kndeveloper.mambaGrowth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHu7OV5HNB8zNAcxG30GakLIaLxVDBLLg',
    appId: '1:688370582507:web:ea568061bee0127c6a8fae',
    messagingSenderId: '688370582507',
    projectId: 'mamba-growth-kn',
    authDomain: 'mamba-growth-kn.firebaseapp.com',
    storageBucket: 'mamba-growth-kn.firebasestorage.app',
    measurementId: 'G-81S3RXDXQ6',
  );
}
